// SPDX-License-Identifier: MIT
// Generated by app-payment `vk_to_solidity`. Do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Groth16 verifier for a fixed circuit. 9 public inputs.
contract DepositVerifier {
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 constant alphax = 0x151bb7ccaaf61ea0360cb9462cfe01289ce402702706c7d4214d066cdd1c9c8d;
    uint256 constant alphay = 0x0e59b41cfe63adc7f34d374349008c565fda96819f3e0ea6edd90291ed3b712d;
    uint256 constant betax1 = 0x2a3d2ce96fc97f14436f73b7b82ceb78603a0865b8bf54025a39952943903d24;
    uint256 constant betax2 = 0x1d87bd17e66c2df38753c24dec3fb23078d5884832c3070638374559fe55b74d;
    uint256 constant betay1 = 0x0c4674f649ab82a23c19a5d203f2b9b1c17c9de0214dee4e597ecd83de6d75ca;
    uint256 constant betay2 = 0x1ff5b661033bae27e9c7d9dde5c58b09490f6870de9e222d5c68c433c74b8523;
    uint256 constant gammax1 = 0x24d05b24ceba967841f846f387f59935204304dce9291baed4ee0499cd1c3ffb;
    uint256 constant gammax2 = 0x19eb0d47fac3b6694bf1a9e5cce291b3f665fc9c739af411a087b2520699bb6c;
    uint256 constant gammay1 = 0x0cef7a98a9192f64891202d9767debf8ee0727e3efe56dbe1f04f67c12aa5a79;
    uint256 constant gammay2 = 0x110d7f9ec9f42d6212ab653972c132661c3904711eaabc5005d1007662ef03e4;
    uint256 constant deltax1 = 0x14f4c5468e34aa4b77cbc32f418d93f75df769d8887e703a4f1d3b1e9b2c4fa2;
    uint256 constant deltax2 = 0x1b31a11f43d36ef0ca41565a87bdd75b8895e60b6c4284a0638a1b3f6aa8318f;
    uint256 constant deltay1 = 0x279198ad7db90883c75c18008f3a8d71e057c0ff3034393369e6d9bf7ea9103e;
    uint256 constant deltay2 = 0x1f3ace2ab9248d5223b3f0a51e680a3f7e84966dd684e77a639df13d910813ff;

    uint256 constant IC0x = 0x246ff1e0882c55129a4b16fcdad6f2f9ea22b8a07f50b2e720a72098a389ae52;
    uint256 constant IC0y = 0x1eba8f18903f87ec6773ee2826750a8a0c4f51d1b64f01c9f2a867798c08ee73;
    uint256 constant IC1x = 0x272e86f4026bea0690cc604a0c50ada6d209cbe1d79c62249b8720fac03f63ae;
    uint256 constant IC1y = 0x0f4ff8f11762a6505c6e7b3c43e689cd1de620b3413f0f91acfde271cc910c16;
    uint256 constant IC2x = 0x2e34b40e764669558d53cdcec143e1b9a9cdded5adfe681a9b224146b8cfcb9f;
    uint256 constant IC2y = 0x2d469d952111ce2ab6322905a89893d02356ac23f8944be18f8c0cd2395387da;
    uint256 constant IC3x = 0x2933378cc35c9f39d65aa064e820f3e17167e2704335ffb67458f08422874292;
    uint256 constant IC3y = 0x00c83e45c770ade0ffa601858788fabad70ef46da97218ed4bfff3e0cbe77b51;
    uint256 constant IC4x = 0x1c7dd6d41b0d530370b786a55242cfcffb136dcd936dc3e1b9e3f7d3bde205cd;
    uint256 constant IC4y = 0x1109f6f04dbec27cc8c922e61b614d4f155d5e8a8e09e28b0d36256cecc5aa48;
    uint256 constant IC5x = 0x2b6876840fb1cc2929ebadaa87f956d497ca7c85e926f66a583f492dc803f762;
    uint256 constant IC5y = 0x0f51f8dd959a3618b45f4338d052aa8114a73b10be577eae85fe7d1ed0105076;
    uint256 constant IC6x = 0x2586bc40fc094dc0819ff50773981dc1c7dd231f4dd33f44f211f36d8549ff65;
    uint256 constant IC6y = 0x125fc18dcef172de8fb4b74b79a2a51457755a49931812a1103509486766f273;
    uint256 constant IC7x = 0x14f236378e3fd225e9fbc1990564ba4895d3521f50f3e64aba621cd7cf51efd2;
    uint256 constant IC7y = 0x037a2cd6a4fb473315e2f0907f28d2886b032ca59f4751184b46526e4ca814c3;
    uint256 constant IC8x = 0x2c313243a3087c89bba03ec32776835b4579e724f0192a063193a8bb3dc0e6f4;
    uint256 constant IC8y = 0x256fa315070f56032eb029f25fd0a8328970c7096ba538fe4156f4a33cdd260f;
    uint256 constant IC9x = 0x116406b20586b7a6370c99ab19a0c89f410becfbd3e3e9029985eddef89fc86e;
    uint256 constant IC9y = 0x15987abdcdc1840f60f9c895f3712c17b2ff24fa1bb6af96a3deb6eb9019886e;

    uint256 public constant NUM_INPUTS = 9;

    /// @notice Verifying key as flat words for batch verification:
    ///         [alpha.x, alpha.y, beta(4), gamma(4), delta(4), IC0.x, IC0.y, IC1.x, IC1.y, …]
    function vkPoints() external pure returns (uint256[] memory p) {
        p = new uint256[](14 + 2 * (NUM_INPUTS + 1));
        p[0] = alphax; p[1] = alphay;
        p[2] = betax1; p[3] = betax2; p[4] = betay1; p[5] = betay2;
        p[6] = gammax1; p[7] = gammax2; p[8] = gammay1; p[9] = gammay2;
        p[10] = deltax1; p[11] = deltax2; p[12] = deltay1; p[13] = deltay2;
        p[14] = IC0x; p[15] = IC0y;
        p[16] = IC1x; p[17] = IC1y;
        p[18] = IC2x; p[19] = IC2y;
        p[20] = IC3x; p[21] = IC3y;
        p[22] = IC4x; p[23] = IC4y;
        p[24] = IC5x; p[25] = IC5y;
        p[26] = IC6x; p[27] = IC6y;
        p[28] = IC7x; p[29] = IC7y;
        p[30] = IC8x; p[31] = IC8y;
        p[32] = IC9x; p[33] = IC9y;
    }

    /// @dev proof = [A.x, A.y, B.x1, B.x2, B.y1, B.y2, C.x, C.y]
    function verifyProof(uint256[8] calldata proof, uint256[9] calldata pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // accumulate vk_x += scalar * (x, y)
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pSignals, pMem) -> isOk {
                let _pPairing := add(pMem, 0)
                let _pVk := add(pMem, 768)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

            g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pSignals, 0)))
            g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pSignals, 32)))
            g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pSignals, 64)))
            g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pSignals, 96)))
            g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pSignals, 128)))
            g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pSignals, 160)))
            g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pSignals, 192)))
            g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pSignals, 224)))
            g1_mulAccC(_pVk, IC9x, IC9y, calldataload(add(pSignals, 256)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))
                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))
                // alpha, beta
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                // vk_x, gamma
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // C, delta
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, 832))

            // all public inputs must be canonical field elements
            checkField(calldataload(add(pubSignals, 0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))
            checkField(calldataload(add(pubSignals, 128)))
            checkField(calldataload(add(pubSignals, 160)))
            checkField(calldataload(add(pubSignals, 192)))
            checkField(calldataload(add(pubSignals, 224)))
            checkField(calldataload(add(pubSignals, 256)))
            let isValid := checkPairing(proof, add(proof, 64), add(proof, 192), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
