// SPDX-License-Identifier: MIT
// Generated by app-payment `vk_to_solidity`. Do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Groth16 verifier for a fixed circuit. 8 public inputs.
contract DepositVerifier {
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 constant alphax = 0x25a8edfe57d9c1804cc1c8841ce06fae1a579ec8ca4a0e97a7829af27b0ed9c2;
    uint256 constant alphay = 0x003cb0812c26e503541e8ccc259f5bcd9a27cc0419ef1778d8c53dca291862fd;
    uint256 constant betax1 = 0x1d806af9c451d1c1b68ccc3f1316e1260dc409b2b9ee8f6bab3dda6523035b13;
    uint256 constant betax2 = 0x2a84b8421516d510d5c9778f3f4afa893dfc304515b1bfca05e946c3643d50c2;
    uint256 constant betay1 = 0x2ea0ad78d7aea02a6773b06769add2d657cc00cd4c3dc2645655be057a97ff00;
    uint256 constant betay2 = 0x1a8d4b895b2c8929d7ad158c9605e75ba1660fcb025d57cabcd197655e546a41;
    uint256 constant gammax1 = 0x0f8f640af5bec6232c2d8f7b6ecc18366e5cf6eeb812716fda2ec14f9a7e17ee;
    uint256 constant gammax2 = 0x14723fea2c4e638149585228bfdb7a16510eddbea2565da7dbff76176bab752f;
    uint256 constant gammay1 = 0x2ef7f26edbca458afb9c94931a467bd6630808ceb711daa75940ae34db7c4dfa;
    uint256 constant gammay2 = 0x0d01e53ef6008c86fd13d1b28be45d65483527d44463b26982fa8284be7b2cc5;
    uint256 constant deltax1 = 0x3017f3d75c086d9fc11c245d974728e799beccceac290e93f9aa0460a8557b7c;
    uint256 constant deltax2 = 0x2393602b727b9c467e24fcde3235c38a112b3332b6a25f237d7a481b2ae132fb;
    uint256 constant deltay1 = 0x05fdde9603fda9784bc6cc66dfb922a1d172e7fd88e79319fbc6557906bc5a8c;
    uint256 constant deltay2 = 0x16b3c2d88bcb8554f9d1e5c27e55cbdca4215dce8597915e5ac8cfe81ae72806;

    uint256 constant IC0x = 0x295a238764ac0659ad9a0ee8db5ccb707e1c2a8d7c69c640886830f68cba190d;
    uint256 constant IC0y = 0x19ffc3b805e7c8f7da23e5db569c28da0f7f51b177319bdc8a2f567cb0bd42d3;
    uint256 constant IC1x = 0x1f0e28fb98548a24a63c51eee2736a3bc425d0a8f3efca2ff99ab20421fc8265;
    uint256 constant IC1y = 0x16487a1e48ce89775b8af5a74890967e1ba01830c68022d5223b4d236955b856;
    uint256 constant IC2x = 0x01e8de596dd3c29f230d4a6fb97bc7865e22c4d81362eaabae1b179a574b299b;
    uint256 constant IC2y = 0x1d32b5ad656b050ce16bccbf60b7ae3dceea95f84ab24603e438c9a7c95f3899;
    uint256 constant IC3x = 0x2beed14edf57d0f7ddf5a397e07f050db639a68d8cf1e7fbbee3bc96e6c10c5a;
    uint256 constant IC3y = 0x21f0faef27984323720d13c310623e21a77ced69070db788b4b7654906d8117e;
    uint256 constant IC4x = 0x12fdcf2a23214843b939c8176c301f050965ab930cb5c0a6541270f8791ed6d0;
    uint256 constant IC4y = 0x1cbf276594faedb87f0c3dce8553223e97d515d6fe1da954c12965aa60279778;
    uint256 constant IC5x = 0x0bd07cb617d89c9eaa9e626886be9e71680766280ee9e594b7d7314537f01a1e;
    uint256 constant IC5y = 0x00f981c0b27f7bddd6b8f6be49efaa384d2a18aecee1da994f0ad3fe939debcd;
    uint256 constant IC6x = 0x2a62a909daefa444025aa8048a8c1ceb9524ae4ba9d2299941338da628dd0126;
    uint256 constant IC6y = 0x2b9e2ef68441bb6beaca9ff3f18691bc71e5ed2c363e6e2084a448726c06767a;
    uint256 constant IC7x = 0x14488e8258a517f5348162dfb4b52590adfcc25a9a8f9dac244c1a27d92b95d4;
    uint256 constant IC7y = 0x15978bdf6ab5ac5c60410eb95d89552a5141c0c1f736ec3276668842e66cdbbf;
    uint256 constant IC8x = 0x2b4ee724eb31d6c8efe29937ba1e8c675b3f4a75232294ae283ad1b6c49edf84;
    uint256 constant IC8y = 0x1caadd37cc9cf16ce7ecf2bedfdc3f7c56d3487a268cb7c6e13ae652a2389ad3;

    uint256 public constant NUM_INPUTS = 8;

    /// @notice Verifying key as flat words for batch verification:
    ///         [alpha.x, alpha.y, beta(4), gamma(4), delta(4), IC0.x, IC0.y, IC1.x, IC1.y, …]
    function vkPoints() external pure returns (uint256[] memory p) {
        p = new uint256[](14 + 2 * (NUM_INPUTS + 1));
        p[0] = alphax; p[1] = alphay;
        p[2] = betax1; p[3] = betax2; p[4] = betay1; p[5] = betay2;
        p[6] = gammax1; p[7] = gammax2; p[8] = gammay1; p[9] = gammay2;
        p[10] = deltax1; p[11] = deltax2; p[12] = deltay1; p[13] = deltay2;
        p[14] = IC0x; p[15] = IC0y;
        p[16] = IC1x; p[17] = IC1y;
        p[18] = IC2x; p[19] = IC2y;
        p[20] = IC3x; p[21] = IC3y;
        p[22] = IC4x; p[23] = IC4y;
        p[24] = IC5x; p[25] = IC5y;
        p[26] = IC6x; p[27] = IC6y;
        p[28] = IC7x; p[29] = IC7y;
        p[30] = IC8x; p[31] = IC8y;
    }

    /// @dev proof = [A.x, A.y, B.x1, B.x2, B.y1, B.y2, C.x, C.y]
    function verifyProof(uint256[8] calldata proof, uint256[8] calldata pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // accumulate vk_x += scalar * (x, y)
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pSignals, pMem) -> isOk {
                let _pPairing := add(pMem, 0)
                let _pVk := add(pMem, 768)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

            g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pSignals, 0)))
            g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pSignals, 32)))
            g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pSignals, 64)))
            g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pSignals, 96)))
            g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pSignals, 128)))
            g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pSignals, 160)))
            g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pSignals, 192)))
            g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pSignals, 224)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))
                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))
                // alpha, beta
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                // vk_x, gamma
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // C, delta
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, 832))

            // all public inputs must be canonical field elements
            checkField(calldataload(add(pubSignals, 0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))
            checkField(calldataload(add(pubSignals, 128)))
            checkField(calldataload(add(pubSignals, 160)))
            checkField(calldataload(add(pubSignals, 192)))
            checkField(calldataload(add(pubSignals, 224)))
            let isValid := checkPairing(proof, add(proof, 64), add(proof, 192), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
