// SPDX-License-Identifier: MIT
// Generated by app-payment `vk_to_solidity`. Do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Groth16 verifier for a fixed circuit. 17 public inputs.
contract Transfer1x3Verifier {
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 constant alphax = 0x0947c50f5620c6917662541f41ab4ebc2d8dc95702eab5a1aec773df5dc1ff6f;
    uint256 constant alphay = 0x09da6833aa992c1d8ccd872ab221a889ddcb521fc84b2f7f6b4d74c16ef3e7ca;
    uint256 constant betax1 = 0x1c69bcb252a1dc54bda0c5a31295b5771da1b806eef257f4fce14e558ee434d6;
    uint256 constant betax2 = 0x269a41b99307ccfd8a68773b51d3282be7041a2911f143a10c84cdcd679b5335;
    uint256 constant betay1 = 0x24db39043c429662379b77342ad897cfa8f6ff04b8744c2aac107f9991c1e628;
    uint256 constant betay2 = 0x19c26e9f1cf67740c74b3b02d83a5704ea5f76b88aba22d428b063d9b7da3199;
    uint256 constant gammax1 = 0x15655feac49a8069f95d7d1e25074a5f077f3115b14a18dd069b25caf150e334;
    uint256 constant gammax2 = 0x22603c91c9138718dc8e99fb8030273c282299acc439ee196c24e18ebffd3d3f;
    uint256 constant gammay1 = 0x1d2779bcde739c492ab35e9251e550e64a79016c4f65b1fbdf66b43be603e4b8;
    uint256 constant gammay2 = 0x2b718f0b03efbe854ab0e36901ced31f742ff06cd64db25698cf7fad26a6545b;
    uint256 constant deltax1 = 0x2d012ab5553b59141b6429b63a825ee4dbe163124601ecbabbfb1cf2609929c8;
    uint256 constant deltax2 = 0x291376ba7f4402f8132e7ef330eb0659c2135b71bb233d0794804e38c3d15cd6;
    uint256 constant deltay1 = 0x166854101f43593c9650a967bc7ef3aad1fb4a9ff105b7728e3c14bb5fbbfda9;
    uint256 constant deltay2 = 0x06e707bedb0524963c8b16b237886bafee4ae8a4e8f312a7734f7f203e262996;

    uint256 constant IC0x = 0x19961d9ffd996f15f33423911db9c7de1c1e64f4727f098474aedfbcb88eef38;
    uint256 constant IC0y = 0x10b3edd661ba793a527a80b3c6e5e43572136ae2671495517bbbdfdde324c1ff;
    uint256 constant IC1x = 0x0da7888c711881d750bf9ca6babdcb479e3d0bf500d2fdbbabbfea0e2aa90f2a;
    uint256 constant IC1y = 0x296ccca4ad992c1acde5391c46f411a5a6ffb12490906bc6231edc934e566aff;
    uint256 constant IC2x = 0x1be12e7b7cca13033e38e40497a577cab069c79ef7e3aa17a3611ca56e026a6b;
    uint256 constant IC2y = 0x2a97c788da57102afd95c47e61fbdae14c107d1b82ae392c056a8679d1de66c1;
    uint256 constant IC3x = 0x0cccc11e2791a4db99425c187ae063697663d56ac76740f593071c1221cc9c45;
    uint256 constant IC3y = 0x259b36de6ddbd7dba48147c92bff5bdd52b6b7456c7698c0246a7565616d3f61;
    uint256 constant IC4x = 0x2a317fb690d4dd692ed6dd9be41048f00cd990070a724338487e38d615f98ae1;
    uint256 constant IC4y = 0x18a61c1a16d1ea23cb5e22fcff931b3142f59ff10981c2a4ff1a1b04be65e250;
    uint256 constant IC5x = 0x286700698266303a99fd9bd00823aa61d0a9a37c8d9653ce5929426223e304a8;
    uint256 constant IC5y = 0x2c9563a2465a908b2618da0769bdb091326fbc1b4fa69a56c7df9f5bc37b0d33;
    uint256 constant IC6x = 0x0b8b4dfc18855a16efe0c36d5952a3c1cb08a5b041813974e6bfb90fcd14f82b;
    uint256 constant IC6y = 0x112a5ec1b90a7203121a0dca1cea9c285f93b0502be30b893fe6019d694bd13d;
    uint256 constant IC7x = 0x263621daa3d03e217c355f1f8a426241a02dc7bfe18be4b3c3688206cbe2eb60;
    uint256 constant IC7y = 0x04412b485eb82796fd75c7541926af50c5015f587108195397a40cf70d379cd2;
    uint256 constant IC8x = 0x2fe3721897c280b1ddec4877f81378f7751f2a4974c5338189babb9f972e4182;
    uint256 constant IC8y = 0x2530e06650c0bb610047e84e7ce0e0692476269813a033eb86a0530cea583cf8;
    uint256 constant IC9x = 0x1cdbf9d90fdcb2e00a0dac927caf5fe7b373e3d6a286f4e6a91682ec8de41923;
    uint256 constant IC9y = 0x1bbbe75e57c7b3e9ecb238b59bc7898a2bd1657a366bf13d128971e2867dea57;
    uint256 constant IC10x = 0x17f3e2e817f7f864fae198e6f63b2ecf4fd177ae44341859f9ca48fa94cba0b1;
    uint256 constant IC10y = 0x2f60b24f097f3e2e69e606ad70b4a4ebe4ff403a4c40888e2c68a7af624e4707;
    uint256 constant IC11x = 0x0350beadcb4f8d1f6e7a7c18af92d434b6626ea55e276caafa5b68cc34463d28;
    uint256 constant IC11y = 0x1c66390a30652d05e9c3138942844257a9a3e52786a8e5b379308d9376abb7a4;
    uint256 constant IC12x = 0x1a01b0ec854c47f92799cca26584fd40420672d7315e8616eccb0667e551733e;
    uint256 constant IC12y = 0x005c8b5aae0c427c130517e7ff543a550e376c0377de0bbf8be58fdb74273f34;
    uint256 constant IC13x = 0x230b55e704a8146e0ee57e87a70328dcb01801f0d2b46447665cc84967f029df;
    uint256 constant IC13y = 0x0d8735e0537b492a2414abcda686b1870c26ab3bf47be17f57fcd9ea9f509c2b;
    uint256 constant IC14x = 0x2ed19fcb135c4b7924ffb36e8a337875c400335867454748f773ecc57bc28d73;
    uint256 constant IC14y = 0x0141ca6d70297ae7ad05ca999e5b25f38f8baa751e1195d94dd6897f30129550;
    uint256 constant IC15x = 0x0ed4e85cd5bb426662e7d3f77626d181d37a8bcef03392b2822dd4723ff96563;
    uint256 constant IC15y = 0x2ad6c47005423952048540b1385f8909a7ce34067883ebedd6b661b1c570a89d;
    uint256 constant IC16x = 0x17ad97eaa7f5cfd5d26044b4e4be8bd9bd34e2b3997376a009bc97d0122f7441;
    uint256 constant IC16y = 0x10e6b147d06eb7f405f5b0c95fb9761f9ed2e088ac74415ce44961e55976f16d;
    uint256 constant IC17x = 0x23f87bd695a5972390abca9d0d84457dbd833c8c0423903b61e8d8e632734f07;
    uint256 constant IC17y = 0x2e296bc07bb2f0c3b8367d977ed55e02507ffbf1da0d4806ed0975c6373235b3;

    uint256 public constant NUM_INPUTS = 17;

    /// @notice Verifying key as flat words for batch verification:
    ///         [alpha.x, alpha.y, beta(4), gamma(4), delta(4), IC0.x, IC0.y, IC1.x, IC1.y, …]
    function vkPoints() external pure returns (uint256[] memory p) {
        p = new uint256[](14 + 2 * (NUM_INPUTS + 1));
        p[0] = alphax; p[1] = alphay;
        p[2] = betax1; p[3] = betax2; p[4] = betay1; p[5] = betay2;
        p[6] = gammax1; p[7] = gammax2; p[8] = gammay1; p[9] = gammay2;
        p[10] = deltax1; p[11] = deltax2; p[12] = deltay1; p[13] = deltay2;
        p[14] = IC0x; p[15] = IC0y;
        p[16] = IC1x; p[17] = IC1y;
        p[18] = IC2x; p[19] = IC2y;
        p[20] = IC3x; p[21] = IC3y;
        p[22] = IC4x; p[23] = IC4y;
        p[24] = IC5x; p[25] = IC5y;
        p[26] = IC6x; p[27] = IC6y;
        p[28] = IC7x; p[29] = IC7y;
        p[30] = IC8x; p[31] = IC8y;
        p[32] = IC9x; p[33] = IC9y;
        p[34] = IC10x; p[35] = IC10y;
        p[36] = IC11x; p[37] = IC11y;
        p[38] = IC12x; p[39] = IC12y;
        p[40] = IC13x; p[41] = IC13y;
        p[42] = IC14x; p[43] = IC14y;
        p[44] = IC15x; p[45] = IC15y;
        p[46] = IC16x; p[47] = IC16y;
        p[48] = IC17x; p[49] = IC17y;
    }

    /// @dev proof = [A.x, A.y, B.x1, B.x2, B.y1, B.y2, C.x, C.y]
    function verifyProof(uint256[8] calldata proof, uint256[17] calldata pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // accumulate vk_x += scalar * (x, y)
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pSignals, pMem) -> isOk {
                let _pPairing := add(pMem, 0)
                let _pVk := add(pMem, 768)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

            g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pSignals, 0)))
            g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pSignals, 32)))
            g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pSignals, 64)))
            g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pSignals, 96)))
            g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pSignals, 128)))
            g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pSignals, 160)))
            g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pSignals, 192)))
            g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pSignals, 224)))
            g1_mulAccC(_pVk, IC9x, IC9y, calldataload(add(pSignals, 256)))
            g1_mulAccC(_pVk, IC10x, IC10y, calldataload(add(pSignals, 288)))
            g1_mulAccC(_pVk, IC11x, IC11y, calldataload(add(pSignals, 320)))
            g1_mulAccC(_pVk, IC12x, IC12y, calldataload(add(pSignals, 352)))
            g1_mulAccC(_pVk, IC13x, IC13y, calldataload(add(pSignals, 384)))
            g1_mulAccC(_pVk, IC14x, IC14y, calldataload(add(pSignals, 416)))
            g1_mulAccC(_pVk, IC15x, IC15y, calldataload(add(pSignals, 448)))
            g1_mulAccC(_pVk, IC16x, IC16y, calldataload(add(pSignals, 480)))
            g1_mulAccC(_pVk, IC17x, IC17y, calldataload(add(pSignals, 512)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))
                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))
                // alpha, beta
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                // vk_x, gamma
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // C, delta
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, 832))

            // all public inputs must be canonical field elements
            checkField(calldataload(add(pubSignals, 0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))
            checkField(calldataload(add(pubSignals, 128)))
            checkField(calldataload(add(pubSignals, 160)))
            checkField(calldataload(add(pubSignals, 192)))
            checkField(calldataload(add(pubSignals, 224)))
            checkField(calldataload(add(pubSignals, 256)))
            checkField(calldataload(add(pubSignals, 288)))
            checkField(calldataload(add(pubSignals, 320)))
            checkField(calldataload(add(pubSignals, 352)))
            checkField(calldataload(add(pubSignals, 384)))
            checkField(calldataload(add(pubSignals, 416)))
            checkField(calldataload(add(pubSignals, 448)))
            checkField(calldataload(add(pubSignals, 480)))
            checkField(calldataload(add(pubSignals, 512)))
            let isValid := checkPairing(proof, add(proof, 64), add(proof, 192), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
