// SPDX-License-Identifier: MIT
// Generated by app-payment `vk_to_solidity`. Do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Groth16 verifier for a fixed circuit. 8 public inputs.
contract WithdrawVerifier {
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 constant alphax = 0x1615363789e15111fe29fb1b551748061d7084e756bb8e2ae012660078bd2109;
    uint256 constant alphay = 0x1227b0f16588630628bcb051b0afa03cf6c6b163d776fed7b46d59f5760a4b28;
    uint256 constant betax1 = 0x2189ae37c3268e4411b6429871e08d9bcb1b3e4d902a0ac8c5708195c10a6aed;
    uint256 constant betax2 = 0x12f823437df181ab3c97f8d30acb1a31b730e03a82e11425a6af2c9c63ce20fa;
    uint256 constant betay1 = 0x00d229a901df09f726123983f2ffa2f2c5cb2a3c8ccb877853de7bc2f0a31c59;
    uint256 constant betay2 = 0x15e8aab52bdc6259bd82f8a6e76eb8ec61c3991ff73b1c9026f85c9e370330a5;
    uint256 constant gammax1 = 0x2792aa962054af0d22e7c48d81166ec9c34b7caf98623166e1a64bf38b9dd6a6;
    uint256 constant gammax2 = 0x2f4d0e434002a2fcc1fe04f8aae4101f90539eca5efb15f02dc602406b1ffa8e;
    uint256 constant gammay1 = 0x138fbbed61b2f3a9cfb93386927209f745be5e291336e2b82440a1216f1ae53e;
    uint256 constant gammay2 = 0x27970000539db2100a85e9fbdaf65a18d5464edd2e8a6d1a65f8ddea625c914d;
    uint256 constant deltax1 = 0x025ffb86279bf391c96804f2f2ac86e38f8c26d409c011ffc60998b19a47aa91;
    uint256 constant deltax2 = 0x173bf28ace14d2cbf1a17210a8071e266b3841d6c35ef0fa3198184dc4b00d17;
    uint256 constant deltay1 = 0x210533dc46341e6da2a8a7ff59b59f88a3d88d9be3733ead35a1b246a8cd69ca;
    uint256 constant deltay2 = 0x2c8085d92ed05eb1492622791da6cfa956b88b151385e6e95bf54915ebaac556;

    uint256 constant IC0x = 0x120c17c26ceae3b2b7e25790748368dd43db7bf4624007ef36bd854558b47559;
    uint256 constant IC0y = 0x123ec5538f5e9799b6b85e54ac014aef133a7891638e7a62f399edbcb9d786e4;
    uint256 constant IC1x = 0x0b4943a1b3b3e5db660cc741cfd842cfe8165222be601e06b6d3c5ff5d05845d;
    uint256 constant IC1y = 0x088178bdb7d89af2011ff447f9005552edf0b2196284cc8882f974e84cf41811;
    uint256 constant IC2x = 0x2bbcfda7a828e967173ce2c84f28b5c2bf17681e0ea0030931be6dcd6e02ff24;
    uint256 constant IC2y = 0x1a311d3f420f1f0d8f316dfa08fa74a93277f641136d2c6ab8605b7c5be74c17;
    uint256 constant IC3x = 0x0ee5cf46d442550b1f0e6f08dadbbcf14c69493d2e3fef8a4edc925be1571201;
    uint256 constant IC3y = 0x1a591906693e607215be40c9174456caa20691842853817d56d7bd00236d0607;
    uint256 constant IC4x = 0x18c396e03631842c0ec9a626fd627ee2cb09830a02496bc7e91f7f43a4d8d56f;
    uint256 constant IC4y = 0x17cd743c7da9de9e368d938ad184e0c9d74a4b0817f2effd0ac9834908ebcc09;
    uint256 constant IC5x = 0x14d8bafce7e3f46c0b0962d12f461e878de6e025fc4149bc8601547dfbcaa3b9;
    uint256 constant IC5y = 0x0191715212979c23352414e23c88f89b33c5d5ae6a575021b17c8736dc321117;
    uint256 constant IC6x = 0x219ba6d986c4e05a732ee641f2e64a130973accc00165f14be5bce01690e7c2a;
    uint256 constant IC6y = 0x1f76dbe6be53d2ba24d5756bde92eed727343490f494186fffce6860c927859a;
    uint256 constant IC7x = 0x2da051d09d3af912a7047d5e0e3d8458fed1aa5adc306598a49817b1caf8dac9;
    uint256 constant IC7y = 0x0fbc971e4fb740016cea4fed26313da2cd2ec4f71f7a5a5939aa7d77a6d09ba8;
    uint256 constant IC8x = 0x1d273d31473486376fd594d28ed7ff7336afaa958e2ffeb720a6803b23dd3dfd;
    uint256 constant IC8y = 0x1437bd0f55ad2145964bfd0e0d5b9174190d470740442a2144774c0eaef1fc7b;

    uint256 public constant NUM_INPUTS = 8;

    /// @notice Verifying key as flat words for batch verification:
    ///         [alpha.x, alpha.y, beta(4), gamma(4), delta(4), IC0.x, IC0.y, IC1.x, IC1.y, …]
    function vkPoints() external pure returns (uint256[] memory p) {
        p = new uint256[](14 + 2 * (NUM_INPUTS + 1));
        p[0] = alphax; p[1] = alphay;
        p[2] = betax1; p[3] = betax2; p[4] = betay1; p[5] = betay2;
        p[6] = gammax1; p[7] = gammax2; p[8] = gammay1; p[9] = gammay2;
        p[10] = deltax1; p[11] = deltax2; p[12] = deltay1; p[13] = deltay2;
        p[14] = IC0x; p[15] = IC0y;
        p[16] = IC1x; p[17] = IC1y;
        p[18] = IC2x; p[19] = IC2y;
        p[20] = IC3x; p[21] = IC3y;
        p[22] = IC4x; p[23] = IC4y;
        p[24] = IC5x; p[25] = IC5y;
        p[26] = IC6x; p[27] = IC6y;
        p[28] = IC7x; p[29] = IC7y;
        p[30] = IC8x; p[31] = IC8y;
    }

    /// @dev proof = [A.x, A.y, B.x1, B.x2, B.y1, B.y2, C.x, C.y]
    function verifyProof(uint256[8] calldata proof, uint256[8] calldata pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // accumulate vk_x += scalar * (x, y)
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pSignals, pMem) -> isOk {
                let _pPairing := add(pMem, 0)
                let _pVk := add(pMem, 768)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

            g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pSignals, 0)))
            g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pSignals, 32)))
            g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pSignals, 64)))
            g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pSignals, 96)))
            g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pSignals, 128)))
            g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pSignals, 160)))
            g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pSignals, 192)))
            g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pSignals, 224)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))
                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))
                // alpha, beta
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                // vk_x, gamma
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // C, delta
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, 832))

            // all public inputs must be canonical field elements
            checkField(calldataload(add(pubSignals, 0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))
            checkField(calldataload(add(pubSignals, 128)))
            checkField(calldataload(add(pubSignals, 160)))
            checkField(calldataload(add(pubSignals, 192)))
            checkField(calldataload(add(pubSignals, 224)))
            let isValid := checkPairing(proof, add(proof, 64), add(proof, 192), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
