// SPDX-License-Identifier: MIT
// Generated by app-payment `vk_to_solidity`. Do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Groth16 verifier for a fixed circuit. 7 public inputs.
contract WithdrawVerifier {
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 constant alphax = 0x00e1b3b13e8b8fadb5615e73a489472fd70ad9b94042367218867fde431a1c33;
    uint256 constant alphay = 0x1edeea23ec1ddf567b2948d1ef56b00848312cc0c17455e0dbdbc18dc4aca7f8;
    uint256 constant betax1 = 0x1e2a0cf618bdab4f0a9b10bef0e6d0e739cac9b4b461c9b016a15eb116234bc9;
    uint256 constant betax2 = 0x23ebbca098512f53af69067de1c04dc67a12383ae59fc304323eed44e88358c4;
    uint256 constant betay1 = 0x09d6ee15c032d9b6d49d154be6ead4ae0149ffd8183d27719f997d3871c72437;
    uint256 constant betay2 = 0x10e7e2962dd404279a28028cb33f3255240a1203018bafdbbea1fdd246a99c37;
    uint256 constant gammax1 = 0x2a21c018ba049cf356808c0c7443f8fdd8c301bb9aa8d567e344a3a76efe43f5;
    uint256 constant gammax2 = 0x0bdcc22b34a55928ec2bd3eb37f4bf3d4eaf2a85815329b055c3cb2960e98267;
    uint256 constant gammay1 = 0x2d5fbc85f1d6987616d69e11649dd9d23d1b65a9242a219716ea50ce758a3015;
    uint256 constant gammay2 = 0x26b317ab789fe6a64fd579d87722d6837ea1c8c369e33f4e79b0b3b7c5a7273c;
    uint256 constant deltax1 = 0x1ad1322eee5aadde0e3596f71cf25cb213745c5d003d2f31bf975ce8126cbbf8;
    uint256 constant deltax2 = 0x1bba9b483949a6f912c86887edc279e4b2c1743064a6b9049f6e98a417f0eeb7;
    uint256 constant deltay1 = 0x2766b6c726cbd7e60619c7aedebb158dcae8c473f53369fc6b4ab7ba6dd28118;
    uint256 constant deltay2 = 0x2d9efa218c457042d81815a9beaa695ac6375ee6ae500bb4bf27709a0acc6266;

    uint256 constant IC0x = 0x1b7929a975c04e62aaa6fab8cda0d0c4fda0551528bc7327abc2e3e97b64de2e;
    uint256 constant IC0y = 0x2719d245cbe457d106d083c0768395a0dad495b9fcf6c3af3a90fcd57636c4b0;
    uint256 constant IC1x = 0x11efbcb148c16db9c67bab469786a5cdfe1cc38fd82fcfbbd76376c4616d1cdc;
    uint256 constant IC1y = 0x15e682eaf2a04ba036b3d5091a36603dcd3e02ef99dac8ce8568a3fbd5ce68c5;
    uint256 constant IC2x = 0x05e849f3a7470928f84b05c2a95cda0532016e546e9bbbca2d69df6fecfdd670;
    uint256 constant IC2y = 0x19db6e9795cba8122570490a1835eb13cfb0fd339e99f311f61f4a388e71f861;
    uint256 constant IC3x = 0x0f71cdd80c796d34f8470e7ea3fafb10cc3838d0a55a87a2ff22964b9b4583e4;
    uint256 constant IC3y = 0x130460f68fca862d8c829ab33cafab00c2367227cb0d9ba39dca6e3e53defecd;
    uint256 constant IC4x = 0x2ad33cd369445fdbf4a60fb72b7e2d790fad25129cd8a35aefa830ad06071197;
    uint256 constant IC4y = 0x1a988aea7162be54f324f2d4da483affa8ed5a43754d21d007d473d5b4083f1f;
    uint256 constant IC5x = 0x1013333d7401e13c81ae476db81c02b8159b4e47c82cb7c47f4360e16f6d6b5a;
    uint256 constant IC5y = 0x19954152c5127e79afaa7bdc836f43834dbdf634e72260bb2fef38b7f4ebbffb;
    uint256 constant IC6x = 0x146d1646d4649040e605165d6407f7cee63e028a6962bcaa92441b8ad5600b5e;
    uint256 constant IC6y = 0x21134b5cd9509894951a3b49178bb370ddb41037dc00a833ebc5fa548f59ad3f;
    uint256 constant IC7x = 0x23a6b3ae36c4eb8c25a757cd0660bb123de039e456a82e4fa224c90dfcc091b8;
    uint256 constant IC7y = 0x0207fd8b032a7db36206e50f1578e57cfb4e8c17d912742a29805ba1c9dbc0ae;

    uint256 public constant NUM_INPUTS = 7;

    /// @dev proof = [A.x, A.y, B.x1, B.x2, B.y1, B.y2, C.x, C.y]
    function verifyProof(uint256[8] calldata proof, uint256[7] calldata pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // accumulate vk_x += scalar * (x, y)
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pSignals, pMem) -> isOk {
                let _pPairing := add(pMem, 0)
                let _pVk := add(pMem, 768)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

            g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pSignals, 0)))
            g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pSignals, 32)))
            g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pSignals, 64)))
            g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pSignals, 96)))
            g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pSignals, 128)))
            g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pSignals, 160)))
            g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pSignals, 192)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))
                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))
                // alpha, beta
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                // vk_x, gamma
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // C, delta
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, 832))

            // all public inputs must be canonical field elements
            checkField(calldataload(add(pubSignals, 0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))
            checkField(calldataload(add(pubSignals, 128)))
            checkField(calldataload(add(pubSignals, 160)))
            checkField(calldataload(add(pubSignals, 192)))
            let isValid := checkPairing(proof, add(proof, 64), add(proof, 192), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
