// SPDX-License-Identifier: MIT
// Generated by app-payment `vk_to_solidity`. Do not edit by hand.
pragma solidity ^0.8.20;

/// @notice Groth16 verifier for a fixed circuit. 7 public inputs.
contract WithdrawVerifier {
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 constant alphax = 0x1f1ec46b1c91ee182de5317488fee41db8af79981401c669b19f2d4d41a98e0b;
    uint256 constant alphay = 0x16e229cd54ed8904b4086ac322b62ef1bc817240ee02c12c923722040bd8acd3;
    uint256 constant betax1 = 0x131fa6c9edb570f2f2f28b6b131aa628b06cc633f0f7b0fea6a7509a00d93000;
    uint256 constant betax2 = 0x2a0e619a22ab15cde250d18a6e5ff28f3ed905338ebf0b67d178c200e6f2cb09;
    uint256 constant betay1 = 0x0bd6209aecd36d37bf44d54416cbfa1df80d7dda9a805d472a9307ca9dbb0ec9;
    uint256 constant betay2 = 0x1218afb0b3bd0a8bb3c7f6e5104f40c3e303c97f6f36fa32099fc25bcab96b30;
    uint256 constant gammax1 = 0x268507721b53adc5d8729cf628d5a750d40bb9c84093211d43a04f77c4b0ee4b;
    uint256 constant gammax2 = 0x1a7f534ee364fe3d69b6495b80b02f7336f37eea9893a4c6ccfdfde583e92ab9;
    uint256 constant gammay1 = 0x30361a2be88db07efef627c373a1b58f1f52b23b9792f919c592fbe79e176e8b;
    uint256 constant gammay2 = 0x166f9a375477704dc070a4dd7cab81bfb96bf179db467a54024d48ea6e7e2be0;
    uint256 constant deltax1 = 0x2d2b49d659a7a96f1f69f07f7c2d06c1261254221be5f81db92165b35d62f842;
    uint256 constant deltax2 = 0x20a0cd9278a73f7947e89c5bfd7d6158e784f68a6e685244f7aeac7bdd0cf0c1;
    uint256 constant deltay1 = 0x002e988a3a5043e65df8d3e114e2cd33b406c5a24b65d89d9a18bd1ecfd9b9aa;
    uint256 constant deltay2 = 0x2cca97dd9f982bd50ef1ade6649dd187cdf15ce35c8354410ab8b01528444931;

    uint256 constant IC0x = 0x0927aca85cce77f0161ec1b229ae37f26be6f8e961672cb3c757a1af3ae8e589;
    uint256 constant IC0y = 0x163ba0e9e1e08864d72bf595e643cc648166434d01ae11e8ee270450a12fc8d7;
    uint256 constant IC1x = 0x22e4932d9a27f0a4590303bdb2dc4d13a992e7bad338e9b912ec761858c575c7;
    uint256 constant IC1y = 0x23ecdadcc659b2e59e1f4a5eca7115e8e752cd1c81597b3386654298d050f3fe;
    uint256 constant IC2x = 0x17179ef28777ec32d6c762e37349017ff40c54c46c83d382d08fbcfc9b04bf11;
    uint256 constant IC2y = 0x211fa09a6c25a7a21b59e34272d8777c9535f6251bb6aca0ae87788200173eec;
    uint256 constant IC3x = 0x017cabd8e4eecb67e7665af1e90eaa9bc17b785bad3ff0d13fe1ebb6a0f6ea9a;
    uint256 constant IC3y = 0x1f77849ce35925e05d703a857b2d6fb41f26edb60fdf0d380e981ac68d3af18a;
    uint256 constant IC4x = 0x1952f09ee384c99908eceb6cd0ed40365566543783fb0b30cb498dc28f9a8417;
    uint256 constant IC4y = 0x144c7e8f682e959a959081d76c165064beb33d609585281ac5f251a35a636a79;
    uint256 constant IC5x = 0x0a1cf557a7cdff56ad31844bf1ab8fa042f5f36fcbd77a0f434b00de944a3e18;
    uint256 constant IC5y = 0x100252a6a54532eb194cfc84c1ad753b1864d3fe68c7640ee5eaa41d9db36a3a;
    uint256 constant IC6x = 0x296275590636681a27d846d6a1e9653393d6420d0669500d60d02302ceb5476a;
    uint256 constant IC6y = 0x24297c4735ff14d4eaa30542b778e872b0976d38c429e554044d07ffc1d5dd0f;
    uint256 constant IC7x = 0x13a6b8060854d59be42d82e526edd5284e20c93974ba16ac93686075c1ded7c6;
    uint256 constant IC7y = 0x26617b1908750da8972a74280917d42098f99d860f7b36550a8e3a37811de47c;

    uint256 public constant NUM_INPUTS = 7;

    /// @notice Verifying key as flat words for batch verification:
    ///         [alpha.x, alpha.y, beta(4), gamma(4), delta(4), IC0.x, IC0.y, IC1.x, IC1.y, …]
    function vkPoints() external pure returns (uint256[] memory p) {
        p = new uint256[](14 + 2 * (NUM_INPUTS + 1));
        p[0] = alphax; p[1] = alphay;
        p[2] = betax1; p[3] = betax2; p[4] = betay1; p[5] = betay2;
        p[6] = gammax1; p[7] = gammax2; p[8] = gammay1; p[9] = gammay2;
        p[10] = deltax1; p[11] = deltax2; p[12] = deltay1; p[13] = deltay2;
        p[14] = IC0x; p[15] = IC0y;
        p[16] = IC1x; p[17] = IC1y;
        p[18] = IC2x; p[19] = IC2y;
        p[20] = IC3x; p[21] = IC3y;
        p[22] = IC4x; p[23] = IC4y;
        p[24] = IC5x; p[25] = IC5y;
        p[26] = IC6x; p[27] = IC6y;
        p[28] = IC7x; p[29] = IC7y;
    }

    /// @dev proof = [A.x, A.y, B.x1, B.x2, B.y1, B.y2, C.x, C.y]
    function verifyProof(uint256[8] calldata proof, uint256[7] calldata pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // accumulate vk_x += scalar * (x, y)
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pSignals, pMem) -> isOk {
                let _pPairing := add(pMem, 0)
                let _pVk := add(pMem, 768)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

            g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pSignals, 0)))
            g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pSignals, 32)))
            g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pSignals, 64)))
            g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pSignals, 96)))
            g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pSignals, 128)))
            g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pSignals, 160)))
            g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pSignals, 192)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))
                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))
                // alpha, beta
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                // vk_x, gamma
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                // C, delta
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, 832))

            // all public inputs must be canonical field elements
            checkField(calldataload(add(pubSignals, 0)))
            checkField(calldataload(add(pubSignals, 32)))
            checkField(calldataload(add(pubSignals, 64)))
            checkField(calldataload(add(pubSignals, 96)))
            checkField(calldataload(add(pubSignals, 128)))
            checkField(calldataload(add(pubSignals, 160)))
            checkField(calldataload(add(pubSignals, 192)))
            let isValid := checkPairing(proof, add(proof, 64), add(proof, 192), pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
