#!/usr/bin/env bash
# Pull everything the web app needs from the rest of the repo:
#   - wasm bindings  -> src/wasm/        (wasm-pack, web target)
#   - proving keys   -> public/keys/     (from artifacts/, produced by `app-tools setup`)
#   - ABIs           -> src/abi/         (from forge out/)
#   - deployments    -> src/deployments/ (from solidity/deployments/<chainId>.json)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
WEB="$ROOT/web"

echo "• building wasm"
(cd "$ROOT/wasm" && wasm-pack build --release --target web --out-dir "$WEB/src/wasm" >/dev/null)
rm -f "$WEB/src/wasm/.gitignore" "$WEB/src/wasm/package.json" "$WEB/src/wasm/README.md"

echo "• copying proving keys"
mkdir -p "$WEB/public/keys"
cp "$ROOT"/artifacts/*.pk "$ROOT"/artifacts/*.vk "$WEB/public/keys/"

# Keys are served with a one-year immutable cache (public/_headers), so a stale browser or CDN
# copy would silently produce proofs the new verifiers reject. Derive a version from the key
# bytes themselves: it changes exactly when the artifacts change, and nobody has to remember to
# bump it. manifest.json carries it to the browser; keysVersion.ts is what the build expects.
echo "• stamping key version"
sha256() { if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d" " -f1; else shasum -a 256 "$1" | cut -d" " -f1; fi }
KEY_DIR="$WEB/public/keys"
ENTRIES=""
for f in $(ls "$KEY_DIR" | grep -E '\.(pk|vk)$' | sort); do
  ENTRIES="$ENTRIES$f:$(sha256 "$KEY_DIR/$f")\n"
done
KEYS_VERSION=$(printf "$ENTRIES" | { if command -v sha256sum >/dev/null; then sha256sum; else shasum -a 256; fi } | cut -c1-12)
printf "$ENTRIES" | node -e "
const fs=require('fs');
const rows=require('fs').readFileSync(0,'utf8').trim().split('\n').filter(Boolean);
const files=Object.fromEntries(rows.map(r=>{const i=r.lastIndexOf(':');return [r.slice(0,i), r.slice(i+1)]}));
fs.writeFileSync('$KEY_DIR/manifest.json', JSON.stringify({version:'$KEYS_VERSION',generated:new Date().toISOString(),files},null,1)+'\n');
fs.writeFileSync('$WEB/src/keysVersion.ts',
  '// Generated by scripts/sync.sh from the artifacts/ key bytes. Do not edit by hand.\n'+
  'export const EXPECTED_KEYS_VERSION = ' + JSON.stringify('$KEYS_VERSION') + '\n');
"
echo "  keys version $KEYS_VERSION"

echo "• building contracts + copying ABIs"
(cd "$ROOT/solidity" && forge build >/dev/null)
mkdir -p "$WEB/src/abi"
for c in APP TestToken; do
  node -e "const a=require('$ROOT/solidity/out/$c.sol/$c.json');require('fs').writeFileSync('$WEB/src/abi/$c.json',JSON.stringify(a.abi,null,1))"
done
cp "$WEB/src/abi/APP.json" "$ROOT/aggregator/abi/APP.json"
cp "$WEB/src/abi/APP.json" "$ROOT/auditor/abi/APP.json"

echo "• copying deployments"
mkdir -p "$WEB/src/deployments"
cp "$ROOT"/solidity/deployments/*.json "$WEB/src/deployments/" 2>/dev/null || echo "  (no deployments yet)"
ls "$WEB/src/deployments"
echo "done"
