[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
app-payment = { path = "../payment" }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
getrandom = { version = "0.2", features = ["js"] }
ark-serialize.workspace = true
ark-std.workspace = true
ark-ff.workspace = true
ark-ec.workspace = true
ark-groth16.workspace = true
ark-crypto-primitives.workspace = true
ark-bn254.workspace = true
ark-ed-on-bn254.workspace = true
rand_chacha.workspace = true
